[package]
name = "slippay_2_0"
version = "0.1.0"
edition = "2021"

[dependencies]
# Segurança
ed25519-dalek = "1.0"
rand = "0.7"
sha2 = "0.10"
aes-gcm = "0.10"

# Blockchain Solana
solana-client = "1.18.26"
solana-sdk = "1.18.26"
spl-token = { version = "4.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "2.3", features = ["no-entrypoint"] }

# Banco de dados / PostgreSQL / auditoria
sqlx = { version = "0.6", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "decimal"
] }

rust_decimal = "1.33.0"
rust_decimal_macros = "1.33.0"

# Tempo / datas
chrono = { version = "0.4", features = ["serde"] }

# API REST
axum = "0.7"
tokio = { version = "1", features = ["full"] }

# Serialização
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# UUID
uuid = { version = "1", features = ["v4", "serde"] }

# Erros e utilitários
anyhow = "1.0"

